"""Camera-ready review analysis: the full compute disclosure, from the committed run records.

Why this exists: the paper's `\\Ngpuhours` (src/paper.py) is the grid's training compute only
(the sum of train_gpu_hours over the 45 runs in artifacts/runs.csv). This script adds the
grid's synthesis, the phase-1 sweep and the committed extension runs, from committed files
only, and writes one small macro file.

Inputs (all committed):
  artifacts/runs.csv             train_gpu_hours (one value per run, repeated per T row) and
                                 synth_gpu_hours (one value per (run, T) row) of the 45-run grid
  runs/sweep_*/run.json          gpu_hours of the 20 phase-1 learning-rate proxies
  runs-v1.1/*/run.json,
  runs-v1.3/*/run.json           gpu_hours of the extension training runs whose records are in
                                 the repository (276M budget, 90k/180k retraining, D3 LR sweep,
                                 variable-prompt run). v1.4/v1.5 runs are not committed and are
                                 therefore NOT counted: the extension figure is a lower bound.

The GPU-hours are sums of each job's wall-clock time. Several small jobs often shared one GPU,
so the sums over-count exclusive GPU time (REPRODUCE.md, "Hardware and compute disclosure").

    python3 src/camera_ready_release.py [--tex OTHER.tex]
    # -> artifacts-camera/release_compute.json and artifacts-camera/numbers_cr_release.tex

Supplementary analysis for the reviews; the paper does not use its outputs (the paper's
generated inputs come from src/paper*.py, src/figures.py and src/s0_figure.py only).
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "artifacts-camera")


def m(name: str, val: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{val}}}\n"


def run_json_hours(pattern: str) -> tuple[int, float, set[str]]:
    files = sorted(glob.glob(os.path.join(REPO, pattern)))
    tot, devices = 0.0, set()
    for f in files:
        r = json.load(open(f))
        tot += float(r.get("gpu_hours", 0.0))
        if r.get("device"):
            devices.add(str(r["device"]))
    return len(files), tot, devices


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", default=os.path.join(OUT, "numbers_cr_release.tex"))
    a = ap.parse_args()

    rows = list(csv.DictReader(open(os.path.join(REPO, "artifacts", "runs.csv"))))
    train = {}
    synth = 0.0
    for r in rows:
        train[(r["config"], r["seed"])] = float(r["train_gpu_hours"])
        synth += float(r["synth_gpu_hours"])
    n_grid = len(train)
    grid_train = sum(train.values())

    n_sweep, sweep, dev_sweep = run_json_hours("runs/sweep_*/run.json")
    n_v11, ext11, dev11 = run_json_hours("runs-v1.1/*/run.json")
    n_v13, ext13, dev13 = run_json_hours("runs-v1.3/*/run.json")
    _, _, dev_grid = run_json_hours("runs/[ABC][0-9]_[0-9]/run.json")
    devices = dev_grid | dev_sweep | dev11 | dev13
    assert len(devices) == 1, devices      # every committed record names one device type

    main_total = grid_train + synth + sweep
    rec = {
        "grid_runs": n_grid, "grid_train_gpu_hours": grid_train,
        "grid_synth_gpu_hours": synth, "grid_synth_cells": len(rows),
        "sweep_runs": n_sweep, "sweep_gpu_hours": sweep,
        "main_study_gpu_hours": main_total,
        "extension_runs_committed": n_v11 + n_v13,
        "extension_train_gpu_hours_committed": ext11 + ext13,
        "device": devices.pop(),
        "note": "wall-clock sums; jobs sometimes shared a GPU, so these over-count exclusive "
                "GPU time. Extension figure counts committed run.json files only (v1.1, v1.3).",
    }
    os.makedirs(OUT, exist_ok=True)
    json.dump(rec, open(os.path.join(OUT, "release_compute.json"), "w"), indent=2)

    tex = ["% GENERATED by src/camera_ready_release.py from artifacts/runs.csv, runs/sweep_*/run.json,\n"
           "% runs-v1.1/*/run.json and runs-v1.3/*/run.json. Do not edit; rerun the script.\n",
           m("NcrrGridRuns", str(n_grid)),
           m("NcrrGridTrainGpuh", f"{grid_train:.1f}"),
           m("NcrrGridSynthGpuh", f"{synth:.1f}"),
           m("NcrrSweepRuns", str(n_sweep)),
           m("NcrrSweepGpuh", f"{sweep:.1f}"),
           m("NcrrMainGpuh", f"{main_total:.1f}"),
           m("NcrrExtRuns", str(n_v11 + n_v13)),
           m("NcrrExtTrainGpuh", f"{ext11 + ext13:.1f}"),
           m("NcrrDevice", rec["device"].replace("NVIDIA ", "NVIDIA~"))]
    body = "".join(tex)
    for path in {a.tex, os.path.join(OUT, "numbers_cr_release.tex")}:
        with open(path, "w") as fh:
            fh.write(body)
    print(body, end="")


if __name__ == "__main__":
    main()
