"""Camera-ready: the last macros the integrated paper needs, from committed artifacts only.

The camera-ready plan (notes/camera_ready_plan.md, items O1, O3 and the ws2F-10 figure check)
left four gaps that no other generator fills. This script closes them. It uses the standard
library only, reads committed files only and writes one macro file.

  \\NcrLedgerRefine        identity-ledger refinement row at the precision of its figure bar
                           (results/artifacts-v1.2/identity_ledger.json ledger.steps_T1_to_T16.gain;
                           \\NabsSIMgain prints the same value at 3 decimals)
  \\NcrGam{Mid,Hi}{sim,ci,wer}
                           speaker-contrastive guidance at gamma = 1.0 and 2.0, formatted exactly
                           as \\NcrGuide* (gamma = 0.5) in src/camera_ready_search.py
                           (results/artifacts-v1.2/s4_guidance.json per_gamma)
  \\NcrCfg*                the pre-registered v1.5 classifier-free-guidance check
                           (results/artifacts-v1.5/cfg_gate.json, verdict NEITHER)
  \\NcrCtxItems            items in the prompt-length sweep (results/artifacts-v1.2/s1_context.json)

    python3 src/camera_ready_integrate.py [--tex OTHER.tex]
    # -> results/artifacts-camera/numbers_cr_extra.tex (and a copy at --tex)

Supplementary analysis for the reviews; the paper does not use its outputs (the paper's
generated inputs come from src/paper*.py, src/figures.py and src/s0_figure.py only).
"""
from __future__ import annotations

import argparse
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "results", "artifacts-camera")
A12 = os.path.join(REPO, "results", "artifacts-v1.2")
A15 = os.path.join(REPO, "results", "artifacts-v1.5")


def fmt_ci(ci) -> str:                       # as src/camera_ready_search.py fmt_ci
    return "[{:.4f}, {:.4f}]".format(*ci)


def load(*p):
    with open(os.path.join(*p)) as f:
        return json.load(f)


def macros() -> str:
    L = []
    A = lambda k, v: L.append(f"\\newcommand{{\\Ncr{k}}}{{{v}}}\n")

    # identity ledger: refinement row at the figure's precision (ws2F-10: table == figure)
    led = load(A12, "identity_ledger.json")["ledger"]["steps_T1_to_T16"]
    A("LedgerRefine", f"{led['gain']:+.4f}")

    # speaker-contrastive guidance at the two larger weights (plan O1, INT-1)
    s4 = load(A12, "s4_guidance.json")
    assert s4["gammas"] == [0.5, 1.0, 2.0], s4["gammas"]
    for g, t in (("1.0", "Mid"), ("2.0", "Hi")):
        p = s4["per_gamma"][g]
        A(f"Gam{t}sim", f"{p['d_sim']:+.4f}")
        A(f"Gam{t}ci", fmt_ci(p["ci"]))
        A(f"Gam{t}wer", f"{p['d_wer_points']:+.2f}")
    A("GamRuns", str(s4["n_runs"]))

    # pre-registered classifier-free-guidance check (plan O3, PREREGISTRATION-v1.5 sec. 4(c))
    cfg = load(A15, "cfg_gate.json")
    assert cfg["VERDICT"] == "NEITHER", cfg["VERDICT"]
    pre = cfg["preconditions"]
    A("CfgRuns", str(len(cfg["runs"])))
    A("CfgEvalItems", str(cfg["n_eval"]))
    A("CfgGamma", cfg["gamma_selected_on_split"]["weight"].replace("p", "."))
    A("CfgRatio", f"{pre['A_guided_mean']:.2f}$\\times$")
    A("CfgRatioci", "[{:.2f}, {:.2f}]".format(*cfg["A_guided_ci"]))
    A("CfgRatioUnguided", f"{pre['A_unguided_mean']:.2f}$\\times$")
    A("CfgDsim", f"{cfg['delta_sim']['mean']:+.4f}")
    A("CfgDsimci", fmt_ci(cfg["delta_sim"]["ci"]))
    A("CfgDwer", f"{cfg['delta_wer']['mean']:+.4f}")
    A("CfgDwerci", fmt_ci(cfg["delta_wer"]["ci"]))

    # prompt-length sweep: items that have all four prompt lengths
    A("CtxItems", str(load(A12, "s1_context.json")["n_items"]))

    hdr = ("% GENERATED by src/camera_ready_integrate.py from results/artifacts-v1.2/{identity_ledger,\n"
           "% s4_guidance,s1_context}.json and results/artifacts-v1.5/cfg_gate.json.\n"
           "% Do not edit; edit the source and rerun.\n")
    return hdr + "".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", help="also write the macro file here (e.g. the paper repo)")
    a = ap.parse_args()
    tex = macros()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "numbers_cr_extra.tex"), "w") as f:
        f.write(tex)
    if a.tex:
        with open(a.tex, "w") as f:
            f.write(tex)
    print(tex, end="")


if __name__ == "__main__":
    main()
