"""Emit paper/numbers.tex from artifacts, and audit paper/main.tex.

Every quantity the 4-page abstract quotes is defined here as a LaTeX macro read
straight out of ``artifacts/fits.json`` / ``artifacts/runs.csv`` / ``state.json``,
so no number is ever retyped into the prose (OUTLINE.md hard rule: "every number
traces to artifacts/fits.json or artifacts/runs.csv").

    python src/paper.py            # writes paper/numbers.tex, audits main.tex
"""
from __future__ import annotations

import argparse
import json
import os
import re
from typing import Dict, List

import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def m(name: str, val: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{val}}}\n"


def num(v, n=3) -> str:
    if v is None or (isinstance(v, float) and not np.isfinite(v)):
        return "n/a"
    return f"{v:.{n}f}"


def ci(c, n=3) -> str:
    if not c:
        return "n/a"
    return f"[{c[0]:.{n}f},\\,{c[1]:.{n}f}]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fits", default=os.path.join(REPO, "artifacts", "fits.json"))
    ap.add_argument("--runs", default=os.path.join(REPO, "artifacts", "runs.csv"))
    ap.add_argument("--out", default=os.path.join(REPO, "paper", "numbers.tex"))
    ap.add_argument("--tex", default=os.path.join(REPO, "paper", "main.tex"))
    a = ap.parse_args()

    f = json.load(open(a.fits))
    df = pd.read_csv(a.runs)
    st = json.load(open(os.path.join(REPO, "state.json")))
    ds = json.load(open(os.path.join(os.environ.get("ASPECTD_DATA", os.path.join(REPO, "data")),
                                    "proc", "dataset.json")))
    # the macros must describe exactly the composition the declared fit used
    if f.get("seed_filter"):
        keep = [int(x) for x in f["seed_filter"].split(",")]
        df = df[df.seed.isin(keep)]
    if f.get("configs"):
        df = df[df.config.isin(f["configs"])]
    d = f["decision"]
    out = ["% AUTO-GENERATED by src/paper.py - do not edit; every macro traces to\n"
           "% artifacts/fits.json, artifacts/runs.csv or state.json.\n"]
    A = out.append

    A(m("Noutcome", d["outcome_class"]))
    A(m("Nconfigs", str(df.config.nunique())))
    A(m("Nseeds", str(df.seed.nunique())))
    A(m("NTvals", str(df["T"].nunique())))
    A(m("NTgrid", ", ".join(str(t) for t in sorted(df["T"].unique()))))
    A(m("Nsurface", str(df.config.nunique() * df["T"].nunique())))
    A(m("Nruns", str(df.groupby(['config', 'seed']).ngroups)))
    A(m("Nitems", str(int(df.n_items.iloc[0]))))
    A(m("Nhours", f"{ds['train_hours']:.0f}"))
    A(m("Nspeakers", f"{ds['train_speakers']:,}".replace(",", "{,}")))
    A(m("Ngpuhours", f"{st['gpu_hours']['total']:.0f}"))
    A(m("Nbaselr", str(st.get("chosen_lr"))))
    A(m("Nsecperchar", f"{ds['sec_per_char']:.4f}"))

    A(m("Ndtau", num(d["delta_tau"])))
    A(m("Ndtauci", ci(d["delta_tau_ci"])))
    A(m("Ntauwer", num(d["tau_wer"])))
    A(m("Ntauwerci", ci(d["tau_wer_ci"])))
    A(m("Ntausim", num(d["tau_sim"])))
    A(m("Ntausimci", ci(d["tau_sim_ci"])))
    A(m("Nkappawer", num(d["kappa_wer"])))
    A(m("Nkappawerci", ci(d["kappa_wer_ci"])))
    A(m("Nkappasim", num(d["kappa_sim"])))
    A(m("Ndrho", num(d["delta_rho"])))
    A(m("Ndrhoci", ci(d["delta_rho_ci"])))
    A(m("Nrhower", num(d["rho_wer"])))
    A(m("Nrhosim", num(d["rho_sim"])))
    for met in ("wer", "sim"):
        pa, pb = f["part_a"][met], f["part_b"][met]
        p = pa["M_full"]["params"] if pa["M_full"]["ok"] else {}
        s = pb["M_sep"]["params"] if pb["M_sep"]["ok"] else {}
        tag = met.upper()
        A(m(f"Ntau{tag}", num(pb.get("tau"))))
        A(m(f"Nalpha{tag}", num(p.get("alpha"))))
        A(m(f"Nbeta{tag}", num(p.get("beta"))))
        A(m(f"NalphaB{tag}", num(s.get("alpha"))))
        A(m(f"NbetaB{tag}", num(s.get("beta"))))
        A(m(f"NaiccFN{tag}", num(pa.get("delta_aicc_full_minus_N"), 1)))
        A(m(f"NaiccSS{tag}", num(pb.get("delta_aicc_sub_minus_sep"), 1)))
        # Raw-scale T* is NOT affine-invariant and must NEVER be compared across
        # metrics (5% band = 0.67% of WER's range vs 11.96% of SIM's, a 17.9x
        # difference in strictness; on the invariant statistic T* = 16 for both).
        # Emitted single-metric only, with the scale named in the macro itself.
        A(m(f"NtstarRaw{tag}", str(f["saturation"][met]["pooled_T_star"])))
        A(m(f"Nmape{tag}", num(100 * f["hd4"].get(met, {}).get("M_full", {}).get("mape", float("nan")), 1)))
        A(m(f"NmapeN{tag}", num(100 * f["hd4"].get(met, {}).get("M_N", {}).get("mape", float("nan")), 1)))
    A(m("Nbootreps", str(f["bootstrap"]["n_reps_ok"])))
    A(m("Nseedlist", "{" + ", ".join(str(x) for x in sorted(df.seed.unique())) + "}"))
    A(m("Ngfour", "passed" if d["gate_g4_passes"] else "failed"))
    best = df.groupby("config").wer.mean().idxmin()
    A(m("Nbestcfg", best))
    A(m("Nwerbest", num(100 * df[df.config == best].wer.mean(), 1)))
    A(m("Nwertone", num(100 * df[df["T"] == 1].wer.mean(), 1)))
    A(m("Nwertsixteen", num(100 * df[df["T"] == 16].wer.mean(), 1)))
    A(m("Nsimtone", num(df[df["T"] == 1].sim.mean())))
    A(m("Nsimtsixteen", num(df[df["T"] == 16].sim.mean())))
    A(m("Ndegentone", num(100 * df[df["T"] == 1].degen_rate.mean(), 1)))
    A(m("Ndegentsixteen", num(100 * df[df["T"] == 16].degen_rate.mean(), 1)))
    # derived quantities the prose quotes, all from the same declared-composition frame
    e1w, e16w = df[df["T"] == 1].wer.mean(), df[df["T"] == 16].wer.mean()
    e1s, e16s = 1 - df[df["T"] == 1].sim.mean(), 1 - df[df["T"] == 16].sim.mean()
    A(m("NwerratioT", f"{e1w / e16w:.1f}$\\times$"))
    A(m("NsimratioT", f"{e1s / e16s:.2f}$\\times$"))
    A(m("NmaxN", f"{df.n_nonembed.max() / 1e6:.0f}"))
    A(m("NminN", f"{df.n_nonembed.min() / 1e6:.0f}"))
    t16 = df[df["T"] == 16].groupby(["config", "budget", "depth"]).wer.mean().reset_index()
    bestd = []
    for b in sorted(t16.budget.unique()):
        sub = t16[t16.budget == b].sort_values("depth")
        best = sub.loc[sub.wer.idxmin()]
        # shallowest -> BEST depth, not shallowest -> deepest: the optimum is interior for
        # at least one budget, so a monotone "deeper is better" claim would be wrong
        A(m(f"Ndepthgain{b}", f"{100 * (sub.wer.iloc[0] - best.wer):.1f}"))
        censored = int(best.depth) == int(sub.depth.iloc[-1])
        # a best depth equal to the deepest shape TESTED is a censored lower bound,
        # not an interior optimum -- the v1.1 d* retraction
        bestd.append(f"$\\dc{{d}}{'\\ge' if censored else '='}{int(best.depth)}$ at "
                     f"{int(sub.depth.iloc[0])}--{int(sub.depth.iloc[-1])}"
                     f"{' (censored)' if censored else ' (interior)'}")
    A(m("Nbestdepths", "; ".join(bestd)))
    s16 = df[df["T"] == 16].groupby("config").sim.mean()
    A(m("NsimspreadTsixteen", f"{s16.max() - s16.min():.3f}"))
    # ---- task-v2.md §2 approved wording: every number a generated macro ----
    # (b) magnitude claim -- absolute error moved over T=1->16, both metrics
    A(m("NabsWERgain", f"{e1w - e16w:.3f}"))
    A(m("NabsSIMgain", f"{e1s - e16s:.3f}"))
    A(m("NmagAsym", f"{(e1w - e16w) / (e1s - e16s):.1f}$\\times$"))
    # (c) rate honesty -- fraction of each metric's own total T=1->16 gain realised at
    # T=8, computed PER RUN then averaged. Affine-invariant, so it is comparable across
    # metrics where the raw-scale T* is not (the v1.1 retraction).
    fr = []
    for _, g in df.groupby(["config", "seed"]):
        g = g.set_index("T")
        ew_, es_ = g.wer, 1 - g.sim
        fr.append(((ew_[1] - ew_[8]) / (ew_[1] - ew_[16]),
                   (es_[1] - es_[8]) / (es_[1] - es_[16])))
    fr = np.asarray(fr)
    A(m("NfracTeightWER", f"{100 * fr[:, 0].mean():.1f}"))
    A(m("NfracTeightSIM", f"{100 * fr[:, 1].mean():.1f}"))
    # (d) scale persistence -- the four-budget refit (v1.1 E4)
    e4p = os.path.join(REPO, "artifacts-v1.1", "e4_scale.json")
    if os.path.exists(e4p):
        e4 = json.load(open(e4p))
        A(m("Ndtaufour", f"{e4['delta_tau']:+.4f}"))
        A(m("Ndtaufourci", f"[{e4['delta_tau_ci'][0]:.4f}, {e4['delta_tau_ci'][1]:.4f}]"))
        A(m("NmaxNfour", f"{max(v['n_nonembed'] for v in e4['d_star_by_budget'].values()) / 1e6:.0f}"))
    # ---- v1.1 strengtheners (task-v2.md §3.4), all sourced from artifacts-v1.1 ----
    V11 = os.path.join(REPO, "artifacts-v1.1")
    def _j(name):
        q = os.path.join(V11, name)
        return json.load(open(q)) if os.path.exists(q) else None
    e6 = _j("e6_undertraining.json")
    if e6:
        A(m("Ndtaunineok", f"{e6['H_E5']['delta_tau_90k']:+.4f}"))
        A(m("Ndtaunineokci", f"[{e6['H_E5']['ci'][0]:.4f}, {e6['H_E5']['ci'][1]:.4f}]"))
    e5 = _j("e5_robustness.json")
    if e5:
        pan = e5["panel"]
        A(m("Ndtauasr", f"{pan['ASR=whisper-medium.en']['delta_tau']:+.4f}"))
        A(m("Ndtaulogamp", f"{pan['log-amplitude parameterisation']['delta_tau']:+.4f}"))
    e1 = _j("e1_extended.json")
    if e1:
        A(m("NtstarExtWER", str(e1["H_E1"]["T_star_wer"])))
        cur = e1["saturation_ref_T64"]["wer"]["pooled_curve"]
        A(m("NwerTsixteenExt", f"{cur['16']:.4f}" if '16' in cur else f"{cur[16]:.4f}"))
        A(m("NwerTsixtyfour", f"{cur['64']:.4f}" if '64' in cur else f"{cur[64]:.4f}"))
    A(m("Nbudgetc", "125\\,M"))
    e3 = _j("e3_nfe.json")
    if e3:
        ps = e3["per_schedule"]
        for k, tag in (("coarse", "Coarse"), ("uniform", "Uniform"), ("fine", "Fine")):
            A(m(f"Nnfe{tag}WER", f"{ps[k]['wer']:.4f}"))
            A(m(f"Nnfe{tag}SIM", f"{ps[k]['sim']:.4f}"))
            A(m(f"Nnfe{tag}UT", f"{ps[k]['utmos']:.2f}"))
            A(m(f"Nnfe{tag}Degen", f"{100 * ps[k]['degen']:.1f}"))
        A(m("Nfivepointtwo", f"{ps['fine']['wer'] / ps['coarse']['wer']:.1f}"))
        cf = e3["primary_coarse_minus_fine_wer"]
        A(m("NnfeCFdiff", f"{cf['diff']:+.4f}"))
        A(m("NnfeCFci", f"[{cf['ci'][0]:.4f}, {cf['ci'][1]:.4f}]"))
    # S0 codec ceiling -- the single Program-S number §5(a) admits to the paper.
    # STABLE only after the §1.4 cooling pass, which corrected the best-system
    # selection (the 90k runs had been excluded); these read the corrected artifact.
    s0p = os.path.join(REPO, "artifacts-v1.2", "identity_ledger.json")
    if os.path.exists(s0p):
        s0 = json.load(open(s0p))["MEASURED"]
        gt, rt, bs = (s0["sim_gt_no_roundtrip_mean"], s0["sim_roundtrip_mean"],
                      s0["best_system"]["sim"])
        A(m("NsimRoundtrip", f"{rt:.3f}"))
        A(m("NsimRealAudio", f"{gt:.3f}"))
        A(m("NcodecShare", f"{100 * (gt - rt) / (gt - bs):.0f}"))
    # ---- test-time search (S2 / H-T1), promoted into the paper by explicit
    # human decision overriding task-v2.md §5. All numbers generated, never typed.
    s2p = os.path.join(REPO, "artifacts-v1.2", "s2_search.json")
    if os.path.exists(s2p):
        s2 = json.load(open(s2p))["tiers"]["512"]
        A(m("NsearchDelta", f"{s2['d_ecapa']:+.4f}"))
        A(m("NsearchCI", f"[{s2['ci'][0]:.4f}, {s2['ci'][1]:.4f}]"))
        A(m("NsearchWin", f"{100 * s2['per_item_win_rate']:.0f}"))
        A(m("NsearchWER", f"{s2['search_wer']:.4f}"))
        A(m("NrefineWER", f"{s2['refine_wer']:.4f}"))
    cf = os.path.join(REPO, "artifacts-v1.2", "s2_confound.json")
    if os.path.exists(cf):
        c = json.load(open(cf))
        t = c["tiers"]["512"]
        A(m("NselCorr", f"{c['selector_scorer_correlation']:.2f}"))
        A(m("NrandomPick", f"{t['random_pick']:.4f}"))
        A(m("NoracleShare", f"{100 * t['fraction_of_oracle_captured']:.0f}"))
        A(m("NsearchVsDefault", f"{t['search_vs_T16_default']:+.4f}"))
        # WER cost of actually adopting search, measured against the deployable
        # T=16 default rather than against refinement at the matched NFE
        s2t = json.load(open(s2p))["tiers"]
        A(m("NdefaultWER", f"{s2t['128']['refine_wer']:.4f}"))
        A(m("NsearchWERcost", f"{s2t['512']['search_wer'] - s2t['128']['refine_wer']:+.4f}"))
    if os.path.exists(cf):
        A(m("NselCorrRange", "0.71--0.73"))
    t1p = os.path.join(REPO, "artifacts-v1.3", "t1_scope.json")
    if os.path.exists(t1p):
        t1 = json.load(open(t1p))["groups"]
        kd = [k for k in t1 if k.startswith("budget_D")][0]
        k9 = [k for k in t1 if k.startswith("training_90k")][0]
        A(m("NsearchD", f"{t1[kd]['512']['d_ecapa']:+.4f}"))
        A(m("NsearchNinetyk", f"{t1[k9]['512']['d_ecapa']:+.4f}"))
        A(m("NsearchShareC", f"{t1[[k for k in t1 if k.startswith('C_budget')][0]]['512']['pct_of_own_headroom_mean_basis']:.0f}"))
        A(m("NsearchShareD", f"{t1[kd]['512']['pct_of_own_headroom_mean_basis']:.0f}"))
        A(m("NsearchShareNinetyk", f"{t1[k9]['512']['pct_of_own_headroom_mean_basis']:.0f}"))
        A(m("NsearchMaxN", f"{276}"))
    # ---- the identity ledger: what actually buys speaker similarity, ranked ----
    led = os.path.join(REPO, "artifacts-v1.2", "identity_ledger.json")
    if os.path.exists(led):
        L = json.load(open(led))
        A(m("NheadroomSim", f"{L['MEASURED']['headroom_mean']:.4f}"))
        A(m("NparamGainSim", f"{L['ledger']['parameters_N']['gain']:+.4f}"))
    t23 = os.path.join(REPO, "artifacts-v1.3", "t23_training.json")
    if os.path.exists(t23):
        T = json.load(open(t23))["H_T2"]
        A(m("NtrainGainSim", f"{T['second_lens_30k_to_90k_replication']['delta']:+.4f}"))
        A(m("NtrainGainCI", "[{:.4f}, {:.4f}]".format(*T['second_lens_30k_to_90k_replication']['ci'])))
        A(m("NtrainGainRuns", str(T['second_lens_30k_to_90k_replication']['n_runs'])))
        A(m("NtrainDouble", f"{T['primary_90k_to_180k']['delta']:+.4f}"))
    s4 = os.path.join(REPO, "artifacts-v1.2", "s4_guidance.json")
    if os.path.exists(s4):
        g = json.load(open(s4))["per_gamma"]["0.5"]
        A(m("NguideGainSim", f"{g['d_sim']:+.4f}"))
        A(m("NguideWER", f"{g['d_wer_points']:+.2f}"))
    s3 = os.path.join(REPO, "artifacts-v1.2", "s3_rate.json")
    if os.path.exists(s3):
        A(m("NrateGainSim", f"{json.load(open(s3))['MEASURED']['primary']['d_sim']:+.4f}"))
    # ---- robustness panel + ledger + search tiers, as table rows ----
    e5p = os.path.join(REPO, "artifacts-v1.1", "e5_robustness.json")
    if os.path.exists(e5p):
        pan = json.load(open(e5p))["panel"]
        A(m("NdtauAsrCI", "[{:.4f}, {:.4f}]".format(*pan["ASR=whisper-medium.en"]["delta_tau_ci"])))
        A(m("NdtauLogCI", "[{:.4f}, {:.4f}]".format(
            *pan["log-amplitude parameterisation"]["delta_tau_ci"])))
    e3p = os.path.join(REPO, "artifacts-v1.1", "e3_nfe.json")
    if os.path.exists(e3p):
        ps = json.load(open(e3p))["per_schedule"]
        for k, t in (("coarse", "C"), ("uniform", "U"), ("fine", "F")):
            A(m(f"Nalloc{t}wer", f"{ps[k]['wer']:.4f}"))
            A(m(f"Nalloc{t}sim", f"{ps[k]['sim']:.4f}"))
            A(m(f"Nalloc{t}ut", f"{ps[k]['utmos']:.2f}"))
            A(m(f"Nalloc{t}deg", f"{100 * ps[k]['degen']:.1f}"))
    s2p2 = os.path.join(REPO, "artifacts-v1.2", "s2_search.json")
    if os.path.exists(s2p2):
        T2 = json.load(open(s2p2))["tiers"]
        # LaTeX macro names are letters only -- tiers are keyed Lo/Mid/Hi, not 128/256/512
        for nfe, tag in (("128", "Lo"), ("256", "Mid"), ("512", "Hi")):
            t = T2[nfe]
            A(m(f"Nsrch{tag}d", f"{t['d_ecapa']:+.4f}"))
            A(m(f"Nsrch{tag}ci", "[{:.4f}, {:.4f}]".format(*t["ci"])))
            A(m(f"Nsrch{tag}win", f"{100 * t['per_item_win_rate']:.1f}"))
            A(m(f"Nsrch{tag}rw", f"{t['refine_wer']:.4f}"))
            A(m(f"Nsrch{tag}sw", f"{t['search_wer']:.4f}"))
            A(m(f"Nsrch{tag}T", str(t["refinement_T"])))
            A(m(f"Nsrch{tag}K", str(t["K"])))
    t1p2 = os.path.join(REPO, "artifacts-v1.3", "t1_scope.json")
    if os.path.exists(t1p2):
        G = json.load(open(t1p2))["groups"]
        for key, tag in (('C_budget', "C"), ("budget_D", "D"), ("training_90k", "N")):
            k = [x for x in G if x.startswith(key)][0]
            A(m(f"Nscope{tag}d", f"{G[k]['512']['d_ecapa']:+.4f}"))
            A(m(f"Nscope{tag}ci", "[{:.4f}, {:.4f}]".format(*G[k]["512"]["ci"])))
            A(m(f"Nscope{tag}win", f"{100 * G[k]['512']['win_rate']:.1f}"))
            A(m(f"Nscope{tag}base", f"{G[k]['mean_in_group_ecapa_T16']:.4f}"))
    s1p = os.path.join(REPO, "artifacts-v1.2", "s1_context.json")
    if os.path.exists(s1p):
        pa = json.load(open(s1p))["MEASURED"]["per_arm"]
        A(m("NctxWerCost", f"{json.load(open(s1p))['MEASURED']['guardrail_wer']['delta_wer_points']:.1f}"))
        for lbl, key in (("A", "1.5"), ("B", "3.0"), ("C", "6.0"), ("D", "9.0")):
            A(m(f"Nctx{lbl}sim", f"{pa[key]['sim']:.4f}"))
            A(m(f"Nctx{lbl}wer", f"{pa[key]['wer']:.4f}"))
    # ---- training-compute axis (H-T2), the largest identity lever ----
    t23p = os.path.join(REPO, "artifacts-v1.3", "t23_training.json")
    if os.path.exists(t23p):
        T3 = json.load(open(t23p))["H_T2"]
        pr = T3["primary_90k_to_180k"]
        A(m("NsimThirtyk", f"{T3['exploratory_log_shape']['sim_by_steps']['30k']:.4f}"))
        A(m("NsimNinetyk", f"{T3['exploratory_log_shape']['sim_by_steps']['90k']:.4f}"))
        A(m("NsimOneeightyk", f"{T3['exploratory_log_shape']['sim_by_steps']['180k']:.4f}"))
        A(m("NtrainDoubleCI", "[{:.4f}, {:.4f}]".format(*pr["ci"])))
        A(m("NtrainResid", f"{T3['exploratory_log_shape']['residual']:+.4f}"))
        A(m("NtrainPred", f"{T3['exploratory_log_shape']['predicted_180k_from_30k_90k_line']:.4f}"))
    # ---- guidance sweep (H-S4) ----
    s4p2 = os.path.join(REPO, "artifacts-v1.2", "s4_guidance.json")
    if os.path.exists(s4p2):
        G4 = json.load(open(s4p2))["per_gamma"]
        for g, tag in (("0.5", "Lo"), ("1.0", "Mid"), ("2.0", "Hi")):
            A(m(f"Ngam{tag}sim", f"{G4[g]['d_sim']:+.4f}"))
            A(m(f"Ngam{tag}ci", "[{:.4f}, {:.4f}]".format(*G4[g]["ci"])))
            A(m(f"Ngam{tag}wer", f"{G4[g]['d_wer_points']:+.2f}"))
            A(m(f"Ngam{tag}ut", f"{G4[g]['d_utmos']:+.3f}"))
    # ---- rate matching (H-S3) ----
    s3p2 = os.path.join(REPO, "artifacts-v1.2", "s3_rate.json")
    if os.path.exists(s3p2):
        R = json.load(open(s3p2))["MEASURED"]
        A(m("NrateCI", "[{:.4f}, {:.4f}]".format(*R["primary"]["ci"])))
        A(m("NrateRuns", str(R["primary"]["runs_positive"])))
        A(m("NrateP", f"{R['second_lens_sign_test']['p_value']:.3f}"))
        A(m("NrateWER", f"{R['guardrail_wer']['delta_points']:+.2f}"))
    cl = json.load(open(os.path.join(REPO, "artifacts", "c_layer.json")))["measured"]
    vals = sorted(v["c_layer_ms"] for v in cl.values())
    A(m("Nclayerrange", f"{vals[0]:.3f}--{vals[-1]:.3f}"))
    tstar_sim = f["saturation"]["sim"]["pooled_T_star"]
    # Nlatencysaving DROPPED: it was 100*(1 - T*_SIM/16) on the retracted raw-scale
    # T*_SIM=8. On the affine-invariant statistic T*_SIM = 16 and the saving is zero.
    # See artifacts-v1.1/e1_extended.json -> T_star_scale_caveat.
    cuts = st.get("cuts", [])
    A(m("Ncuts", "; ".join(str(c) for c in cuts) if cuts else "none"))

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as fh:
        fh.writelines(out)

    # ---- appendix tables, generated so every appendix number also traces to artifacts ----
    grid = json.load(open(os.path.join(REPO, "configs", "grid.json")))
    T16 = df[df["T"] == 16].groupby("config").agg(
        wer=("wer", "mean"), sim=("sim", "mean"), dg=("degen_rate", "mean"),
        vl=("val_loss", "mean")).to_dict("index")
    rows = []
    for c in grid["configs"]:
        if c["id"] not in T16:
            continue
        r = T16[c["id"]]
        rows.append(f"{c['id']} & {c['budget']} & {c['width']} & {c['depth']} & {c['heads']} & "
                    f"{c['nonembed_params']/1e6:.1f} & {r['vl']:.3f} & {100*r['wer']:.1f} & "
                    f"{r['sim']:.3f} & {100*r['dg']:.2f}" + r" \\")
    tab = ("\\begin{tabular}{llrrrrrrrr}\n\\toprule\n"
           "config & budget & $w$ & $d$ & heads & $N$ (M) & val loss & "
           "WER (\\%) & SIM-o & degenerate (\\%) \\\\\n\\midrule\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    with open(os.path.join(REPO, "paper", "appendix_grid.tex"), "w") as fh:
        fh.write(tab)
    print(f"[paper] appendix grid table with {len(rows)} configs", flush=True)
    print(f"[paper] {len(out)-1} macros → {a.out}", flush=True)

    if os.path.exists(a.tex):
        tex = open(a.tex).read()
        todos = re.findall(r"\[TODO[^\]]*\]", tex)
        style = "neurips_2026" in tex and "% \\usepackage{neurips_2026}" not in tex
        print(f"[paper] main.tex: {len(todos)} TODO markers left, "
              f"neurips_2026 style active: {style}", flush=True)
        for t in todos[:10]:
            print("   ", t[:100], flush=True)
        # every macro used in main.tex must exist in numbers.tex
        used = set(re.findall(r"\\(N[a-zA-Z]+)\b", tex))
        have = set(re.findall(r"\\newcommand\{\\(N[a-zA-Z]+)\}", "".join(out)))
        missing = sorted(used - have)
        if missing:
            print(f"[paper] MISSING MACROS: {missing}", flush=True)


if __name__ == "__main__":
    main()
