"""Emit paper/numbers.tex from artifacts, and audit paper/main.tex.

Every quantity the 4-page abstract quotes is defined here as a LaTeX macro read
straight out of ``artifacts/fits.json`` / ``artifacts/runs.csv`` / ``state.json``,
so no number is ever retyped into the prose (OUTLINE.md hard rule: "every number
traces to artifacts/fits.json or artifacts/runs.csv").

    python src/paper.py            # writes paper/numbers.tex, audits main.tex
"""
from __future__ import annotations

import argparse
import json
import os
import re
from typing import Dict, List

import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def m(name: str, val: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{val}}}\n"


def num(v, n=3) -> str:
    if v is None or (isinstance(v, float) and not np.isfinite(v)):
        return "n/a"
    return f"{v:.{n}f}"


def ci(c, n=3) -> str:
    if not c:
        return "n/a"
    return f"[{c[0]:.{n}f},\\,{c[1]:.{n}f}]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fits", default=os.path.join(REPO, "artifacts", "fits.json"))
    ap.add_argument("--runs", default=os.path.join(REPO, "artifacts", "runs.csv"))
    ap.add_argument("--out", default=os.path.join(REPO, "paper", "numbers.tex"))
    ap.add_argument("--tex", default=os.path.join(REPO, "paper", "main.tex"))
    a = ap.parse_args()

    f = json.load(open(a.fits))
    df = pd.read_csv(a.runs)
    st = json.load(open(os.path.join(REPO, "state.json")))
    ds = json.load(open(os.path.join(os.environ.get("ASPECTD_DATA", "/home/ubuntu/data"),
                                    "proc", "dataset.json")))
    # the macros must describe exactly the composition the declared fit used
    if f.get("seed_filter"):
        keep = [int(x) for x in f["seed_filter"].split(",")]
        df = df[df.seed.isin(keep)]
    if f.get("configs"):
        df = df[df.config.isin(f["configs"])]
    d = f["decision"]
    out = ["% AUTO-GENERATED by src/paper.py - do not edit; every macro traces to\n"
           "% artifacts/fits.json, artifacts/runs.csv or state.json.\n"]
    A = out.append

    A(m("Noutcome", d["outcome_class"]))
    A(m("Nconfigs", str(df.config.nunique())))
    A(m("Nseeds", str(df.seed.nunique())))
    A(m("NTvals", str(df["T"].nunique())))
    A(m("NTgrid", ", ".join(str(t) for t in sorted(df["T"].unique()))))
    A(m("Nsurface", str(df.config.nunique() * df["T"].nunique())))
    A(m("Nruns", str(df.groupby(['config', 'seed']).ngroups)))
    A(m("Nitems", str(int(df.n_items.iloc[0]))))
    A(m("Nhours", f"{ds['train_hours']:.0f}"))
    A(m("Nspeakers", f"{ds['train_speakers']:,}".replace(",", "{,}")))
    A(m("Ngpuhours", f"{st['gpu_hours']['total']:.0f}"))
    A(m("Nbaselr", str(st.get("chosen_lr"))))
    A(m("Nsecperchar", f"{ds['sec_per_char']:.4f}"))

    A(m("Ndtau", num(d["delta_tau"])))
    A(m("Ndtauci", ci(d["delta_tau_ci"])))
    A(m("Ntauwer", num(d["tau_wer"])))
    A(m("Ntauwerci", ci(d["tau_wer_ci"])))
    A(m("Ntausim", num(d["tau_sim"])))
    A(m("Ntausimci", ci(d["tau_sim_ci"])))
    A(m("Nkappawer", num(d["kappa_wer"])))
    A(m("Nkappawerci", ci(d["kappa_wer_ci"])))
    A(m("Nkappasim", num(d["kappa_sim"])))
    A(m("Ndrho", num(d["delta_rho"])))
    A(m("Ndrhoci", ci(d["delta_rho_ci"])))
    A(m("Nrhower", num(d["rho_wer"])))
    A(m("Nrhosim", num(d["rho_sim"])))
    for met in ("wer", "sim"):
        pa, pb = f["part_a"][met], f["part_b"][met]
        p = pa["M_full"]["params"] if pa["M_full"]["ok"] else {}
        s = pb["M_sep"]["params"] if pb["M_sep"]["ok"] else {}
        tag = met.upper()
        A(m(f"Ntau{tag}", num(pb.get("tau"))))
        A(m(f"Nalpha{tag}", num(p.get("alpha"))))
        A(m(f"Nbeta{tag}", num(p.get("beta"))))
        A(m(f"NalphaB{tag}", num(s.get("alpha"))))
        A(m(f"NbetaB{tag}", num(s.get("beta"))))
        A(m(f"NaiccFN{tag}", num(pa.get("delta_aicc_full_minus_N"), 1)))
        A(m(f"NaiccSS{tag}", num(pb.get("delta_aicc_sub_minus_sep"), 1)))
        A(m(f"Ntstar{tag}", str(f["saturation"][met]["pooled_T_star"])))
        A(m(f"Nmape{tag}", num(100 * f["hd4"].get(met, {}).get("M_full", {}).get("mape", float("nan")), 1)))
        A(m(f"NmapeN{tag}", num(100 * f["hd4"].get(met, {}).get("M_N", {}).get("mape", float("nan")), 1)))
    A(m("Nbootreps", str(f["bootstrap"]["n_reps_ok"])))
    A(m("Nseedlist", "{" + ", ".join(str(x) for x in sorted(df.seed.unique())) + "}"))
    A(m("Ngfour", "passed" if d["gate_g4_passes"] else "failed"))
    best = df.groupby("config").wer.mean().idxmin()
    A(m("Nbestcfg", best))
    A(m("Nwerbest", num(100 * df[df.config == best].wer.mean(), 1)))
    A(m("Nwertone", num(100 * df[df["T"] == 1].wer.mean(), 1)))
    A(m("Nwertsixteen", num(100 * df[df["T"] == 16].wer.mean(), 1)))
    A(m("Nsimtone", num(df[df["T"] == 1].sim.mean())))
    A(m("Nsimtsixteen", num(df[df["T"] == 16].sim.mean())))
    A(m("Ndegentone", num(100 * df[df["T"] == 1].degen_rate.mean(), 1)))
    A(m("Ndegentsixteen", num(100 * df[df["T"] == 16].degen_rate.mean(), 1)))
    # derived quantities the prose quotes, all from the same declared-composition frame
    e1w, e16w = df[df["T"] == 1].wer.mean(), df[df["T"] == 16].wer.mean()
    e1s, e16s = 1 - df[df["T"] == 1].sim.mean(), 1 - df[df["T"] == 16].sim.mean()
    A(m("NwerratioT", f"{e1w / e16w:.1f}$\\times$"))
    A(m("NsimratioT", f"{e1s / e16s:.2f}$\\times$"))
    A(m("NmaxN", f"{df.n_nonembed.max() / 1e6:.0f}"))
    t16 = df[df["T"] == 16].groupby(["config", "budget", "depth"]).wer.mean().reset_index()
    bestd = []
    for b in sorted(t16.budget.unique()):
        sub = t16[t16.budget == b].sort_values("depth")
        best = sub.loc[sub.wer.idxmin()]
        # shallowest -> BEST depth, not shallowest -> deepest: the optimum is interior for
        # at least one budget, so a monotone "deeper is better" claim would be wrong
        A(m(f"Ndepthgain{b}", f"{100 * (sub.wer.iloc[0] - best.wer):.1f}"))
        bestd.append(f"$\\dc{{d}}={int(best.depth)}$ at {int(sub.depth.iloc[0])}--{int(sub.depth.iloc[-1])}")
    A(m("Nbestdepths", "; ".join(bestd)))
    s16 = df[df["T"] == 16].groupby("config").sim.mean()
    A(m("NsimspreadTsixteen", f"{s16.max() - s16.min():.3f}"))
    cl = json.load(open(os.path.join(REPO, "artifacts", "c_layer.json")))["measured"]
    vals = sorted(v["c_layer_ms"] for v in cl.values())
    A(m("Nclayerrange", f"{vals[0]:.3f}--{vals[-1]:.3f}"))
    tstar_sim = f["saturation"]["sim"]["pooled_T_star"]
    A(m("Nlatencysaving", f"{100 * (1 - tstar_sim / 16):.0f}"))
    cuts = st.get("cuts", [])
    A(m("Ncuts", "; ".join(str(c) for c in cuts) if cuts else "none"))

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as fh:
        fh.writelines(out)

    # ---- appendix tables, generated so every appendix number also traces to artifacts ----
    grid = json.load(open(os.path.join(REPO, "configs", "grid.json")))
    T16 = df[df["T"] == 16].groupby("config").agg(
        wer=("wer", "mean"), sim=("sim", "mean"), dg=("degen_rate", "mean"),
        vl=("val_loss", "mean")).to_dict("index")
    rows = []
    for c in grid["configs"]:
        if c["id"] not in T16:
            continue
        r = T16[c["id"]]
        rows.append(f"{c['id']} & {c['budget']} & {c['width']} & {c['depth']} & {c['heads']} & "
                    f"{c['nonembed_params']/1e6:.1f} & {r['vl']:.3f} & {100*r['wer']:.1f} & "
                    f"{r['sim']:.3f} & {100*r['dg']:.2f}" + r" \\")
    tab = ("\\begin{tabular}{llrrrrrrrr}\n\\toprule\n"
           "config & budget & \\wc{$w$} & \\dc{$d$} & heads & $N$ (M) & val loss & "
           "WER (\\%) & SIM-o & Degen (\\%) \\\\\n\\midrule\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    with open(os.path.join(REPO, "paper", "appendix_grid.tex"), "w") as fh:
        fh.write(tab)
    print(f"[paper] appendix grid table with {len(rows)} configs", flush=True)
    print(f"[paper] {len(out)-1} macros → {a.out}", flush=True)

    if os.path.exists(a.tex):
        tex = open(a.tex).read()
        todos = re.findall(r"\[TODO[^\]]*\]", tex)
        style = "neurips_2026" in tex and "% \\usepackage{neurips_2026}" not in tex
        print(f"[paper] main.tex: {len(todos)} TODO markers left, "
              f"neurips_2026 style active: {style}", flush=True)
        for t in todos[:10]:
            print("   ", t[:100], flush=True)
        # every macro used in main.tex must exist in numbers.tex
        used = set(re.findall(r"\\(N[a-zA-Z]+)\b", tex))
        have = set(re.findall(r"\\newcommand\{\\(N[a-zA-Z]+)\}", "".join(out)))
        missing = sorted(used - have)
        if missing:
            print(f"[paper] MISSING MACROS: {missing}", flush=True)


if __name__ == "__main__":
    main()
