"""Generate the v1.5 macros and the compute-trend table from artifacts, never by hand.

Claim 2: refinement's intelligibility share saturates while its identity share does not.
Every number here is recomputed from the scored runs at generation time, including the
second-recogniser column, so the table cannot drift from the measurements.

Resampling unit matters and is stated rather than assumed. Seeds within a configuration are
not draws from configuration space, so the bootstrap clusters on configuration (effective
n = 3) and resamples evaluation items as a second dimension. That is wider than treating the
nine runs as independent, and it is the honest interval.

    python src/paper_v15.py     # -> paper/numbers_v15.tex, paper/tab_trend.tex
"""
from __future__ import annotations

import json
import os

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAPER = os.path.join(REPO, "paper")
OUT = os.path.join(REPO, "results", "artifacts-v1.5")
CFG, SEEDS = ("C1", "C3", "C5"), (0, 1, 2)
SUF = {"30k": "", "90k": "_90k", "180k": "_180k"}
WER_FLOOR, SIM_CEIL = 0.0344830, 0.5553695
BOOT_RNG, N_BOOT = 7331, 1000


def _items(run, T):
    for root in ("runs", "runs-v1.1", "runs-v1.3", "runs-v1.4"):
        p = os.path.join(REPO, "results", root, run, f"synth_T{T}", "scores.json")
        if os.path.exists(p):
            return {d["item"]: d for d in json.load(open(p))["items"]}
    return None


def _asr2(run, T):
    for root in ("runs", "runs-v1.1", "runs-v1.3", "runs-v1.4"):
        p = os.path.join(REPO, "results", root, run, f"synth_T{T}", "asr2.json")
        if os.path.exists(p):
            return {d["item"]: d["wer"] for d in json.load(open(p))["items"]}
    return None


def load():
    """cache every per-item value once; the bootstrap must not touch the disk"""
    D = {}
    for b in SUF:
        for c in CFG:
            for s in SEEDS:
                r = f"{c}_{s}{SUF[b]}"
                for T in (1, 16):
                    D[(b, c, s, T, "w")] = _items(r, T)
                    D[(b, c, s, T, "a")] = _asr2(r, T)
    return D


def shares(D, b, ids, cfgs, which="w", floor=WER_FLOOR):
    W1 = W16 = S1 = S16 = 0.0
    n = 0
    for c in cfgs:
        for s in SEEDS:
            a, z = D[(b, c, s, 1, "w")], D[(b, c, s, 16, "w")]
            if which == "a":
                aw, zw = D[(b, c, s, 1, "a")], D[(b, c, s, 16, "a")]
                if not (aw and zw):
                    return None
                W1 += np.mean([aw[i] for i in ids]); W16 += np.mean([zw[i] for i in ids])
            else:
                W1 += np.mean([a[i]["wer"] for i in ids]); W16 += np.mean([z[i]["wer"] for i in ids])
            S1 += np.mean([a[i]["sim"] for i in ids]); S16 += np.mean([z[i]["sim"] for i in ids])
            n += 1
    W1, W16, S1, S16 = W1 / n, W16 / n, S1 / n, S16 / n
    return (W1 - W16) / (W1 - floor), (S16 - S1) / (SIM_CEIL - S1)


def main():
    D = load()
    ids = sorted(D[("30k", "C1", 0, 1, "w")])
    rng = np.random.default_rng(BOOT_RNG)
    a2floor = json.load(open(os.path.join(OUT, "g0c_asr2.json")))["wer_mean"]

    M, rows = [], []
    add = lambda k, v: M.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    WORD = {"30k": "Thirtyk", "90k": "Ninetyk", "180k": "Eightyk"}
    pt = {}
    for b in SUF:
        w, s = shares(D, b, ids, CFG)
        wa, _ = shares(D, b, ids, CFG, "a", a2floor)
        reps = []
        for _ in range(N_BOOT):
            cs = [CFG[i] for i in rng.integers(0, len(CFG), len(CFG))]
            ii = [ids[i] for i in rng.integers(0, len(ids), len(ids))]
            r = shares(D, b, ii, cs)
            reps.append(r[0] / r[1])
        ci = [float(np.percentile(reps, 2.5)), float(np.percentile(reps, 97.5))]
        pt[b] = (w, s, w / s, ci, wa)
        add(f"Ngap{WORD[b]}WER", f"{100*w:.1f}")
        add(f"Ngap{WORD[b]}SIM", f"{100*s:.1f}")
        add(f"Ngap{WORD[b]}Ratio", f"{w/s:.2f}$\\times$")
        add(f"Ngap{WORD[b]}Ci", f"[{ci[0]:.2f}, {ci[1]:.2f}]")
        add(f"Ngap{WORD[b]}WERasrTwo", f"{100*wa:.1f}")
        rows.append(f"    {b} & {100*w:.1f}\\% & {100*wa:.1f}\\% & {100*s:.1f}\\% & "
                    f"{w/s:.2f}$\\times$ & {ci[0]:.2f}, {ci[1]:.2f} \\\\")

    # the saturation itself, paired across matched configs and seeds
    dw = 100 * (pt["180k"][0] - pt["90k"][0])
    dwa = 100 * (pt["180k"][4] - pt["90k"][4])
    ds = 100 * (pt["180k"][1] - pt["90k"][1])
    add("NsatWER", f"{dw:+.2f}")
    add("NsatWERasrTwo", f"{dwa:+.2f}")
    add("NsatSIM", f"{ds:+.1f}")
    add("NasrTwoName", "wav2vec2-large-960h-lv60-self")
    add("NasrTwoFloor", f"{a2floor:.4f}")
    add("NtrendRuns", len(CFG) * len(SEEDS))
    add("NtrendBudgets", 3)

    hdr = ("% GENERATED by src/paper_v15.py from the scored runs. Do not edit.\n")
    open(os.path.join(PAPER, "numbers_v15.tex"), "w").write(hdr + "\n".join(M) + "\n")
    body = ("% GENERATED by src/paper_v15.py\n"
            "\\begin{tabular}{lccccc}\n  \\toprule\n"
            "  & \\multicolumn{2}{c}{intelligibility share} & identity & & \\\\\n"
            "  \\cmidrule(lr){2-3}\n"
            "  training & Whisper & \\NasrTwoName & share & ratio & 95\\% CI \\\\\n"
            "  \\midrule\n" + "\n".join(rows) + "\n  \\bottomrule\n\\end{tabular}\n")
    open(os.path.join(PAPER, "tab_trend.tex"), "w").write(body)
    print(f"wrote {len(M)} macros and the trend table")
    for b in SUF:
        w, s, r, ci, wa = pt[b]
        print(f"  {b:<5} intel {100*w:5.1f}% (asr2 {100*wa:5.1f}%)  identity {100*s:5.1f}%  "
              f"ratio {r:.2f}x [{ci[0]:.2f}, {ci[1]:.2f}]")
    print(f"  saturation 90k->180k: WER {dw:+.2f} pp (asr2 {dwa:+.2f} pp), SIM {ds:+.1f} pp")


if __name__ == "__main__":
    main()
